<?php
namespace Odyssey;

class helpfulTools {
    public function console_log($output, $with_script_tags = true) {
        $js_code = 'console.log(' . json_encode($output, JSON_HEX_TAG) . ');';
        if ($with_script_tags) {
            $js_code = '<script>' . $js_code . '</script>';
        }
        echo $js_code;
    }

    public function isImage($filepath) {
        if (@is_array(getimagesize($filepath))) {
            return true;
        } else {
            return false;
        }
    }
}

class Server {
    /**
     * @param string $ServerName The name for the server
     * @param string $Invite A custom invite for the server, created by the server owner.
     * @param array $Icon $Icon[0] represents either a file or an URL. $Icon[1] is the url.
     * @param string $Channels Optional. A JSON request generated by the 'create server' page. This is a list of all the default channels created. Permissions are attached.
     * @param string $Roles Optional. A JSON request generated by the 'create server' page. This is a list of all the default roles created. Permissions are attached.
     */
    public function create(String $ServerName, String $Invite, array $Icon, String $Channels = null, String $Roles = null) {
        if ('URL' == $Icon[0]) {
            if (substr(get_headers($Icon[1])[5], 8, 3) == 200) {
                copy($Icon[1], "../../backend/$ServerName/logo");
                if (isImage("../../backend/$ServerName/logo") == true) {
                    imagepng(imagecreatefromstring("../..backend/$ServerName/logo"), "../..backend/$ServerName/logo.png");
                    $Icon = "../../backend/$ServerName/logo";
                } else {
                    return array(4, false, 'Faulty server logo provided.');
                }
            } else {
                return array(3, false, 'Invalid website.');
            }
        } elseif ('File' == $Icon[0]) {
            if (move_uploaded_file($_FILES['ServerLogo']['tmp_name'], "/../../$ServerName/logo")) {
                if (isImage("../../backend/$ServerName/logo") == true) {
                    imagepng(imagecreatefromstring("../..backend/$ServerName/logo"), "../..backend/$ServerName/logo.png");
                    $Icon = "../../backend/$ServerName/logo";
                } else {
                    return array(4, false, 'Faulty server logo provided.');
                }
            } else {
                return array(4, false, 'Faulty server logo provided.');
            }
        }
        $conn_string = 'host=localhost port=5432 dbname=odyssey user=odysseyuser password=3970746103533296';
        global $database;
        $database = pg_connect($conn_string);
        if (!$database) {
            echo "An error occurred.\n";
            exit;
        } else {
            echo "Blatant disrespect";
        }
        pg_query_params($database, 'INSERT INTO odyssey.servers VALUES($1, $2, $3, $4, $5)', array($ServerName, time(), $Invite, $_COOKIE['Username'], $Icon, null, 1, null, $Roles, $Channels));
        echo pg_last_error($database);
        echo pg_result_error($database);
        echo pg_result_error_field($database);
        echo pg_result_status($database);
        echo pg_connection_status($database);
        return true;
    }
}